---
- name: Update apt cache
  apt: update_cache=yes

- name: Install aptitude (workaround for older ansible)
  shell: "apt-get -y install aptitude"

- name: Upgrade all safe packages
  apt: upgrade=safe

- name: Install apt-transport-https
  apt:
    name: apt-transport-https
    state: present

- name: Add Kubernetes GPG key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Install Microsoft GPG key
  apt_key:
    url: 'https://packages.microsoft.com/keys/microsoft.asc'
    state: present

- name: Install VSCode Repo
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    filename: vscode
    state: present

- name: Install Azure CLI Repo
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli bionic main
    filename: az
    state: present

- name: Add Kubernetes APT repos
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes

- name: Get the good stuff
  apt:
    pkg:
      - azure-cli
      - build-essential
      - code
      - default-jdk
      - default-jdk-doc
      - docker.io
      - git
      - hexchat
      - irssi
      - keepassxc
      - kubectl
      - openssh-server
      - python-pip
      - snapd
      - terminator
      - ttf-mscorefonts-installer
      - vagrant
      - vim
      - virtualbox
      - xrdp
      - xubuntu-desktop
      - xubuntu-restricted-extras

- name: Install awscli
  pip:
    name: awscli

- name: Install git-interactive-rebase-tool
  apt:
    deb: "https://github.com/MitMaro/git-interactive-rebase-tool/releases/download/1.0.0/git-interactive-rebase-tool_1.0.0_amd64.deb"

- name: Configure git-interactive-rebase-tool
  shell: "git config --global sequence.editor interactive-rebase-tool"
  become: yes
  become_user: vagrant

- name: Install kops
  shell: "curl -Lo kops https://github.com/kubernetes/kops/releases/download/$(curl -s https://api.github.com/repos/kubernetes/kops/releases/latest | grep tag_name | cut -d '\"' -f 4)/kops-linux-amd64 && chmod +x ./kops && sudo mv ./kops /usr/local/bin/"
  become: yes

- name: Install caprine, discord, slack and yakyak snaps
  shell: |
    snap install caprine
    snap install discord
    snap install yayak
    snap install slack --classic

- name: Make it xubuntu
  shell: |
    mkdir ~/.config
    echo 'xfce4-session' > ~/.xsession
    cp -R /etc/xdg/xdg-xubuntu/* ~/.config
  become: yes
  become_user: vagrant

- name: Fix xrdp
  shell: "sed -i 's/new_cursors=true/new_cursors=false/g' /etc/xrdp/xrdp.ini"
  become: yes

- name: Create local .bin
  shell: mkdir ~/.bin
  become: yes
  become_user: vagrant

- name: Get pycharm
  get_url:
    url: "https://download.jetbrains.com/python/pycharm-community-2019.1.tar.gz"
    dest: /home/vagrant
  
- name: Install pycharm
  shell: "tar -C ~/.bin -xvf /home/vagrant/pycharm*.tar.gz"
  become: yes
  become_user: vagrant

- name: Get IntelliJ IDEA
  get_url:
    url: "https://download.jetbrains.com/idea/ideaIC-2019.1.tar.gz"
    dest: /home/vagrant

- name: Install IntelliJ IDEA
  shell: "tar -C ~/.bin -xvf /home/vagrant/idea*.tar.gz"
  become: yes
  become_user: vagrant