---
- name: Update apt cache
  apt: update_cache=yes

- name: Install aptitude (workaround for older ansible)
  shell: "apt-get -y install aptitude"

- name: Upgrade all safe packages
  apt: upgrade=safe

- name: Install apt-transport-https
  apt:
    name: apt-transport-https
    state: present

- name: Install xubuntu packages and a couple of extras
  apt:
    pkg:
      - keepassxc
      - snapd
      - terminator
      - ttf-mscorefonts-installer
      - xubuntu-desktop
      - xubuntu-restricted-extras

- name: Create local .bin
  shell: mkdir ~/.bin
  become: yes
  become_user: "{{ user }}"

- name: Create Desktop folder
  shell: mkdir ~/Desktop
  become: yes
  become_user: "{{ user }}"

- name: Add local user to extra groups 
  user:
    name: "{{ user }}"
    groups:
        - sudo
    append: yes
