---
- name: Install Microsoft GPG key
  apt_key:
    url: 'https://packages.microsoft.com/keys/microsoft.asc'
    state: present

- name: Install VSCode Repo
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    filename: vscode
    state: present

- name: Install development packages
  apt:
    pkg:
      - build-essential
      - code
      - default-jdk
      - default-jdk-doc
      - git
      - kubectl
      - python-pip
      - vim

- name: Install git-interactive-rebase-tool
  apt:
    deb: "https://github.com/MitMaro/git-interactive-rebase-tool/releases/download/1.0.0/git-interactive-rebase-tool_1.0.0_amd64.deb"

- name: Configure git-interactive-rebase-tool
  git_config:
    name: sequence.editor
    scope: global
    value: interactive-rebase-tool
  become: yes
  become_user: "{{ user }}"

- name: Install PyCharm and IntelliJ snaps
  snap:
    name: "{{ item.name }}"
    state: present
    classic: "{{ item.classic }}"
  with_items:
    - { name: pycharm-community, classic: yes}
    - { name: intellij-idea-community, classic: yes}

- name: install Sublime Text 
  block:
   - name: Install sublime GPG key
     apt_key:
      url: 'https://download.sublimetext.com/sublimehq-pub.gpg'

   - name: Install Sublime need packages
     apt:
      pkg:
       - apt-transport-https

   - name: Add Sublime Text Repo
     apt_repository:
      repo: "deb https://download.sublimetext.com/ apt/stable/"
      filename: sublimetext
      state: present

   - name: Install Sublime Text
     apt:
      pkg:
       - sublime-text

  tags: ['sublime']
