---
- name: Get the good stuff
  apt:
    pkg:
      - hexchat
      - irssi
      - snapd


- name: Install Caprine, Discord, and Yakyak snaps
  snap:
    name: "{{ item.name }}"
    state: present
    classic: "{{ item.classic }}"
  with_items:
    - { name: caprine, classic: no }
    - { name: discord, classic: no }
    - { name: yakyak, classic: no }
    - { name: slack, classic: yes }
