---
- name: Install Microsoft GPG key
  apt_key:
    url: 'https://packages.microsoft.com/keys/microsoft.asc'
    state: present

- name: Install Azure CLI Repo
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli bionic main
    filename: az
    state: present

- name: Add Kubernetes GPG key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add Kubernetes APT repos
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes

- name: Install cloud-related packages
  apt:
    pkg:
      - azure-cli
      - kubectl
      - python-pip

- name: Install awscli
  pip:
    name: awscli

- name: Construct part of kops url
  uri:
    url: https://api.github.com/repos/kubernetes/kops/releases/latest
    method: GET
    return_content: yes
    body_format: json
  register: dummy_var
  tags: test1

- name: Install kops
  get_url:
    url: https://github.com/kubernetes/kops/releases/download/{{ dummy_var | json_query('json.tag_name') }}/kops-linux-amd64
    dest: /usr/local/bin/kops
    mode: +x
