---

- hosts: all
  become: True
  gather_facts: True
  roles:
    - { role: common, tags: common }
    - { role: cloud, tags: cloud }
    - { role: communication, tags: communication }
    - { role: devel, tags: devel }
    - { role: rdp, tags: rdp }
    - { role: virtualization, tags: virtualization }
